services:
  Astroforge-frontend:
    build: ./frontend/
    command: npm run dev
    ports:
      - ${EXPOSED_PORT:-80}:5173
    volumes:
      - ./frontend/:/usr/src/Astroforge
      - node_modules:/usr/src/app/node_modules
    container_name: Astroforge-frontend

  Astroforge-backend:
    build: ./backend/
    container_name: Astroforge-backend
    volumes:
      - ./backend
    environment:
      - ${POSTGRES_USER:-dummyuser}
      - ${POSTGRES_PASSWORD:-dummypassword}
      - ${POSTGRES_DB:-dummydb}
      - ${POSTGRES_PORT:-5432}
  db:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes: db:/var/lib/postgresql/
    environment:
      - ${POSTGRES_USER:-dummyuser}
      - ${POSTGRES_PASSWORD:-dummypassword}
      - ${POSTGRES_DB:-dummydb}
      - ${POSTGRES_PORT:-5432}

  redis:
    image: redis:alpine

  volumes:
    - node_modules
    - db